// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_6ndPNAF2IHrksmPxZ5jj2A-sEVruYU',
    appId: '1:888304855609:web:f3bb959ea6b09477fdbbe8',
    messagingSenderId: '888304855609',
    projectId: 'my-travaly-ahmad-5dcb9',
    authDomain: 'my-travaly-ahmad-5dcb9.firebaseapp.com',
    storageBucket: 'my-travaly-ahmad-5dcb9.firebasestorage.app',
    measurementId: 'G-JBSZRM525B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5g1xZIe15M6fP26iMLbb3imLJE-4Gng',
    appId: '1:888304855609:android:3a0b26bb2782a154fdbbe8',
    messagingSenderId: '888304855609',
    projectId: 'my-travaly-ahmad-5dcb9',
    storageBucket: 'my-travaly-ahmad-5dcb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ycaQHjgyiqLuuOLUufwzpxa3qmmRF-0',
    appId: '1:888304855609:ios:a75bdd943d853badfdbbe8',
    messagingSenderId: '888304855609',
    projectId: 'my-travaly-ahmad-5dcb9',
    storageBucket: 'my-travaly-ahmad-5dcb9.firebasestorage.app',
    androidClientId: '888304855609-djtgds29j2lj5li4h10n0dj54s6kih33.apps.googleusercontent.com',
    iosClientId: '888304855609-ho1a188c0iutc8ti06mu4sk5d07938tq.apps.googleusercontent.com',
    iosBundleId: 'com.test.my.travaly.mytravalyahmad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ycaQHjgyiqLuuOLUufwzpxa3qmmRF-0',
    appId: '1:888304855609:ios:50a66aca46c21849fdbbe8',
    messagingSenderId: '888304855609',
    projectId: 'my-travaly-ahmad-5dcb9',
    storageBucket: 'my-travaly-ahmad-5dcb9.firebasestorage.app',
    iosClientId: '888304855609-plcn4odcgv2stgkglgoreo0r50c6o6ot.apps.googleusercontent.com',
    iosBundleId: 'com.test.my.travaly.myTravaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd_6ndPNAF2IHrksmPxZ5jj2A-sEVruYU',
    appId: '1:888304855609:web:83d4b3d052e9895bfdbbe8',
    messagingSenderId: '888304855609',
    projectId: 'my-travaly-ahmad-5dcb9',
    authDomain: 'my-travaly-ahmad-5dcb9.firebaseapp.com',
    storageBucket: 'my-travaly-ahmad-5dcb9.firebasestorage.app',
    measurementId: 'G-VZ2HB3CCRK',
  );

}